/*----------------------------------------------------------------------+
|                                                                       |
|   Current Revision:                                                   |
|    Workfile:
|    Revision:
|                                                                       |
+----------------------------------------------------------------------*/
/*----------------------------------------------------------------------+
|                                                                       |
|                                                                       |
|                                                                       |
|									|
|									|
/*----------------------------------------------------------------------+
|                                                                       |
|   c:\ustation\mdl\nips\rsc\iconstxt.h
|                                                                       |
+----------------------------------------------------------------------*/
#define TXT_iCSm1_icon1	    "icon1"
#define TXT_iCSm2_icon2	    "icon2"
#define TXT_iCSm3_icon3	    "icon3"
#define TXT_iCSm4_icon4	    "icon4"
#define TXT_iCSm5_icon5	    "icon5"
#define TXT_iCSm6_icon6	    "icon6"
#define TXT_iCSm7_icon7	    "icon7"
#define TXT_iCSm8_icon8	    "icon8"
#define TXT_iCSm9_DetailDialog	    "DetailDialog"
#define TXT_iCSm10_Display	    "Display"
