#ifndef _GLOBALS_H
#define _GLOBALS_H

#include <stdlib/stdio.h>
#include <stdlib/stdlib.h>
#include <stdlib/math.h>
#include <stdlib/float.h>
#include <stdlib/string.h>
#include <mdl.h>
#include <msassoc.fdf>
#include <mslocate.fdf>
#include <mselemen.fdf>
#include <mselems.h>
#include <mscell.fdf>
#include <mselmdsc.fdf>
#include <msrmatrx.fdf>
#include <msstate.fdf>
#include <msview.fdf>
#include <dlogman.fdf>
#include <colrname.h>
#include <levels.h>
#include "dlogdids.h"
#include "defs.h"
#include "util.h"
#include "place.h"
#include "cell.h"
#include "plgm5aa.h"
#include "plgm5ab.h"
#include "plgm5ai.h"
#include "plgm5ai2.h"
#include "plgm5aj.h"
#include "plgm5ak.h"
#include "plgm5ak2.h"
#include "plgm5al.h"
#include "plgm5al2.h"
#include "llist.h"
#include "details.h"
#include "sort.h"
#include "display.h"
#include "fileio.h"

#endif
