/*----------------------------------------------------------------------+
|                                                                       |
|   Current Revision:                                                   |
|    Workfile:
|    Revision:
|                                                                       |
+----------------------------------------------------------------------*/
/*----------------------------------------------------------------------+
|                                                                       |
|                                                                       |
|                                                                       |
|									|
|									|
/*----------------------------------------------------------------------+
|                                                                       |
|   c:\ustation\mdl\nips\rsc\icons.h
|                                                                       |
+----------------------------------------------------------------------*/
#define ICONSMALLICONID_1			1
#define ICONSMALLICONID_2			2
#define ICONSMALLICONID_3			3
#define ICONSMALLICONID_4			4
#define ICONSMALLICONID_5			5
#define ICONSMALLICONID_6			6
#define ICONSMALLICONID_7			7
#define ICONSMALLICONID_8			8
#define ICONSMALLICONID_9			9
#define ICONSMALLICONID_10			10
